version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  ignore:
  - dependency-name: System.IO.Abstractions
    versions:
    - 13.2.10
    - 13.2.11
    - 13.2.15
    - 13.2.16
    - 13.2.20
    - 13.2.23
    - 13.2.24
    - 13.2.25
    - 13.2.28
    - 13.2.9
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: JetBrains.Annotations
    versions:
    - 2020.3.0
  - dependency-name: CsvHelper
    versions:
    - 21.3.0
    - 22.1.0
    - 22.1.1
    - 22.1.2
    - 23.0.0
    - 24.0.1
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: SixLabors.ImageSharp
    versions:
    - 1.0.3-alpha.0.8
