name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  build: '$(Build.BuildID)'

# Run on all commits,  except for some folders
trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*
    - scripts/*
    - '**/*.md'

stages:
  - stage: build
    jobs:
      - template: build/azure-pipelines-build.yml
  # - stage: test
  #   jobs:
  #     - template: build/azure-pipelines-test.yml
  # - stage: release
  #   jobs:
  #     - template: build/azure-pipelines-release.yml

# jobs:
#   - job: Linux
#     pool:
#       vmImage: 'ubuntu-latest'
#   - job: macOS
#     pool:
#       vmImage: 'macOS-latest'
#   - job: Windows
#     pool:
#       vmImage: 'windows-latest'

#     strategy:
#       maxParallel: 2
#       matrix:
#         AnyCPU-Debug:
#           buildPlatform: 'Any CPU'
#           buildConfiguration: 'Debug'
#         AnyCPU-Release:
#           buildPlatform: 'Any CPU'
#           buildConfiguration: 'Release'