name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  build: '$(Build.BuildID)'
  system.debug: true
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

# Run on all commits,  except for some folders
trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*
    - scripts/*
    - '**/*.md'

stages:
  - stage: build
    jobs:
      - template: build/azure-pipelines-build.yml
  # - stage: test
  #   jobs:
  #     - template: build/azure-pipelines-test.yml
  # - stage: release
  #   jobs:
  #     - template: build/azure-pipelines-release.yml
