name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  build: '$(Build.BuildID)'
  system.debug: true
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

# Run on all commits,  except for some folders
trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - docs/*
    - scripts/*
    - '**/*.md'

stages:
  - stage: build
    jobs:
      - template: build/azure-pipelines-build.yml
  #- stage: release
      
