- name: GenericRecognizerConfig
  href: xref:AnalysisPrograms.Recognizers.GenericRecognizer.GenericRecognizerConfig

- name: CommonParameters
  href: xref:AnalysisPrograms.Recognizers.Base.CommonParameters

- name: OscillationParameters
  href: xref:AnalysisPrograms.Recognizers.Base.OscillationParameters

- name: HarmonicParameters
  href: xref:AnalysisPrograms.Recognizers.Base.HarmonicParameters

- name: PostProcessingConfig
  href: xref:AudioAnalysisTools.Events.Types.EventPostProcessing.PostProcessingConfig

- name: AnalyzerConfig
  href: xref:AnalysisBase.AnalyzerConfig