//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioTag
    {
        public int AudioTagID { get; set; }
        public System.Guid AudioReadingID { get; set; }
        public string Tag { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public string OldCreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public double StartFrequency { get; set; }
        public double EndFrequency { get; set; }
    
        public virtual AudioReading AudioReading { get; set; }
        public virtual AudioTags_MetaData AudioTags_MetaData { get; set; }
    }
}
