//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioReading
    {
        public AudioReading()
        {
            this.AudioSearchResults = new HashSet<AudioSearchResult>();
            this.Cache_Jobs = new HashSet<Cache_Jobs>();
            this.Processor_JobItems = new HashSet<Processor_JobItems>();
            this.AudioTags = new HashSet<AudioTag>();
            this.ReadReadings = new HashSet<ReadReading>();
        }
    
        public System.DateTime Time { get; set; }
        public string MimeType { get; set; }
        public int HardwareID { get; set; }
        public Nullable<double> EnvironmentalIndex { get; set; }
        public System.Guid AudioReadingID { get; set; }
        public Nullable<System.Guid> DeploymentID { get; set; }
        public Nullable<int> DurationMs { get; set; }
        public int LocalReadingID { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string UploadType { get; set; }
        public string UploadMetaData { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> UploadStartUTC { get; set; }
        public string DataLocation { get; set; }
        public Nullable<long> DataSizeBytes { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<AudioSearchResult> AudioSearchResults { get; set; }
        public virtual ICollection<Cache_Jobs> Cache_Jobs { get; set; }
        public virtual ICollection<Processor_JobItems> Processor_JobItems { get; set; }
        public virtual Deployment Deployment { get; set; }
        public virtual Hardware Hardware { get; set; }
        public virtual ICollection<AudioTag> AudioTags { get; set; }
        public virtual NoiseReducedAudioReading NoiseReducedAudioReading { get; set; }
        public virtual ICollection<ReadReading> ReadReadings { get; set; }
    }
}
