//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deployment
    {
        public Deployment()
        {
            this.AudioReadings = new HashSet<AudioReading>();
            this.RoleDeployments = new HashSet<RoleDeployment>();
            this.DeploymentTags = new HashSet<DeploymentTag>();
            this.Entity_MetaData = new HashSet<Entity_MetaData>();
        }
    
        public System.Guid DeploymentID { get; set; }
        public int HardwareID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateStarted { get; set; }
        public string Description { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public bool IsTest { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsActive { get; set; }
        public int Timeout { get; set; }
        public string ApproxLongitude { get; set; }
        public string ApproxLatitude { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsSensitive { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public byte[] LocationBinary { get; set; }
        public byte[] ApproxLocationBinary { get; set; }
    
        public virtual ICollection<AudioReading> AudioReadings { get; set; }
        public virtual Hardware Hardware { get; set; }
        public virtual ICollection<RoleDeployment> RoleDeployments { get; set; }
        public virtual ICollection<DeploymentTag> DeploymentTags { get; set; }
        public virtual ICollection<Entity_MetaData> Entity_MetaData { get; set; }
    }
}
