//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeploymentTag
    {
        public int DeploymentTagID { get; set; }
        public System.Guid DeploymentID { get; set; }
        public string Tag { get; set; }
        public string OldCreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Deployment Deployment { get; set; }
    }
}
