//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLog
    {
        public System.Guid LogID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Text { get; set; }
        public string ErrorDetails { get; set; }
        public Nullable<int> HardwareID { get; set; }
        public int Type { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
