//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceStatus
    {
        public System.Guid StatusID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<byte> PowerLevel { get; set; }
        public Nullable<long> FreeMemory { get; set; }
        public Nullable<long> MemoryUsage { get; set; }
        public Nullable<int> HardwareID { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
