//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        public Hardware()
        {
            this.AudioReadings = new HashSet<AudioReading>();
            this.Deployments = new HashSet<Deployment>();
            this.DeviceLogs = new HashSet<DeviceLog>();
            this.DeviceSchedules = new HashSet<DeviceSchedule>();
            this.DeviceStatuses = new HashSet<DeviceStatus>();
            this.PhotoReadings = new HashSet<PhotoReading>();
        }
    
        public int HardwareID { get; set; }
        public string UniqueID { get; set; }
        public string FriendlyName { get; set; }
        public bool IsManualDevice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastContacted { get; set; }
    
        public virtual ICollection<AudioReading> AudioReadings { get; set; }
        public virtual ICollection<Deployment> Deployments { get; set; }
        public virtual ICollection<DeviceLog> DeviceLogs { get; set; }
        public virtual ICollection<DeviceSchedule> DeviceSchedules { get; set; }
        public virtual ICollection<DeviceStatus> DeviceStatuses { get; set; }
        public virtual ICollection<PhotoReading> PhotoReadings { get; set; }
    }
}
