//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoReading
    {
        public Nullable<System.DateTime> Time { get; set; }
        public byte[] Data { get; set; }
        public bool Uploaded { get; set; }
        public string MimeType { get; set; }
        public Nullable<int> HardwareID { get; set; }
        public System.Guid PhotoReadingID { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
