//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoZoo.Models.DAO.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor_Types
    {
        public int ProcessorTypeId { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Settings { get; set; }
        public string ProcessorName { get; set; }
        public string LatestVersion { get; set; }
        public string AdditionalData { get; set; }
    }
}
