--- 
# WARNING!!! The keys used below MUST BE EXACTLY the SAME as those declared in the class InitialiseIndexProperties (starting at line 30).

# the root object name maps to the Key property on the IndexProperties class
 
BackgroundNoise:
  Name: Background Noise
  Comment: "Av amplitude of the noise removed from the audio segment using the method of Lamel et al."
  DataType: double
  DefaultValue: -80
  DoDisplay: true
  # SNR.MINIMUM_dB_BOUND_FOR_ZERO_SIGNAL + 10
  NormMin: -50.0
  NormMax: -15.0
  ProjectID: Acoustic Indices
  Units: "dB"
  IncludeInComboIndex: false
  ComboWeight: 0.0
Snr:
  Name: Maximum SNR
  Comment: "Max amplitude of signal envelope after noise removal."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 35.0
  ProjectID: Acoustic Indices
  Units: "dB"
  IncludeInComboIndex: false
  ComboWeight: 0.0
AvgSnrOfActiveFrames:
  Name: av SNR (Active frames)
  Comment: "Av amplitude of active frames in signal envelope after noise removal. Active frames are those with amplitude > threshold 3 dB."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 12.0
  ProjectID: Acoustic Indices
  Units: "dB"
  IncludeInComboIndex: false
  ComboWeight: 0.0
Activity:
  Name: Activity
  Comment: "% of active frames i.e. where SNR exceeds threshold = 3 dB."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 1.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
EventsPerSecond:
  Name: Events per sec
  Comment: "Av number of events per second. An event is any consecutive sequence of active frames having duration > threshold = 100 ms."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 3.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
AvgEventDuration:
  Name: Av Event Duration
  Comment: "Av duration in ms of the events in an audio segment."
  DataType: TimeSpan
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 1000
  ProjectID: Acoustic Indices
  Units: "ms"
  IncludeInComboIndex: false
  ComboWeight: 0.0
HighFreqCover:
  Name: hf Cover
  Comment: "% hf Cover 4000 Hz to 8800 Hz"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 0.2
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
MidFreqCover:
  Name: mf Cover
  Comment: "% mf Cover. 500 Hz to 4000 Hz"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.1
  NormMax: 0.3
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
LowFreqCover:
  Name: lf Cover
  Comment: "% lf Cover. 0 - 500 Hz"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.1
  NormMax: 0.3
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
AcousticComplexity:
  Name: ACI
  Comment: "ACI"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.4
  NormMax: 0.7
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: true
  ComboWeight: 0.2
TemporalEntropy:
  Name: 1-H[t]
  Comment: "1-Ht is a measure of concentration of acoustic energy instead of energy dispersal."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 0.5
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: true
  ComboWeight: 0.3
SqrtTempEntropy:
  Name: Sqrt(1-H[t])
  Comment: "Sqrt(1-Ht) is an attempt to obtain more even distribution of Ht values. NormMax = sqrt(0.5)"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 0.7
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
LogTempEntropy:
  Name: Log(1-H[t])
  Comment: "Log(1-Ht) is an attempt to obtain more even distribution of Ht values. NormMax = log(1 + 0.5)"
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 0.176
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
EntropyOfAverageSpectrum:
  Name: 1-H[avg spectrum]
  Comment: "1-H[spectral avg] is a measure of concentration of acoustic energy in the average spectrum over one minute."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 1.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
EntropyOfVarianceSpectrum:
  Name: 1-H[var spectrum]
  Comment: "1-H[spectral var] is a measure of concentration of acoustic energy in the variance spectrum over one minute."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 1.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
EntropyOfPeaksSpectrum:
  Name: 1-H[peak freq spectrum]
  Comment: "1-H[peak freq] is a measure of concentration of peak frequencies over one minute."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 1.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
EntropyOfCoVSpectrum:
  Name: 1-H[CoV spectrum]
  Comment: "1-H[CoV sp] is a measure of concentration of energy in the Coeff of Variance Spectrum."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0.0
  NormMax: 0.5
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
SptDensity:
  Name: SPT density
  Comment: "Average number of spectral peaks tracks traversing a frame."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: false
  NormMin: 0.0
  NormMax: 2.0
  ProjectID: Acoustic Indices
  Units: ""
  IncludeInComboIndex: false
  ComboWeight: 0.0
#SptPerSecond:
#  Name: av Tracks/Sec
#  Comment: "Average number of spectral tracks per second."
#  DataType: double
#  DefaultValue: 0.0
#  DoDisplay: true
#  NormMin: 0
#  NormMax: 50
#  ProjectID: Acoustic Indices
#  Units: ""
#  IncludeInComboIndex: false
#  ComboWeight: 0.0
EventsTotal:
  Name: Event Count
  Comment: "The total count of acoustic events per minute of recording."
  DataType: double
  DefaultValue: 0.0
  DoDisplay: true
  NormMin: 0
  NormMax: 15.0
  ProjectID: Acoustic Indices
  Units: ""
