---
AnalysisType: Towsey.Acoustic
FileName: 7a667c05-825e-4870-bc4b-9cec98024f5a_101013-0000
BackgroundFilterCoeff: 0.75
SampleRate: 17640
FrameWidth: 512
MinuteOffset: 0
FrameStep: 441
IndexCalculationDuration: 00:00:00.2
...