FRAME_SIZE: 512
FRAME_OVERLAP: 0.5
WINDOW_FUNCTION: Hanning
N_POINT_SMOOTH_FFT: 256
NOISE_REDUCTION_TYPE: modal
SILENCE_RECORDING_PATH: C:\temp
MIN_HZ: 0
MAX_HZ: 0
SEGMENTATION_THRESHOLD_K1: 2
SEGMENTATION_THRESHOLD_K2: 3
K1_K2_LATENCY: 50
VOCAL_GAP: 50
MIN_VOCAL_DURATION: 100
AED_INTENSITY_THRESHOLD: 6
AED_SMALL_AREA_THRESHOLD: 200
DRAW_SONOGRAMS: true