FrameSize: 512
FrameOverlap: 0.5
WindowFunction: Hamming
NpointSmoothFFT: 256
NoiseReductionType: LowestPercentile
SEGMENTATION_THRESHOLD_K1: 2
SEGMENTATION_THRESHOLD_K2: 3
K1_K2_LATENCY: 50
VOCAL_GAP: 50
MIN_VOCAL_DURATION: 100
AED_INTENSITY_THRESHOLD: 6
AED_SMALL_AREA_THRESHOLD: 200