---
SpectralFrameDuration: 0.02
TileWidth: 180
# How to tile, valid values:
# - PanoJsTilingProfile
# - AbsoluteDateTilingProfile
TilingProfile: AbsoluteDateTilingProfile
SpectralIndexScale: 
    - 240
    - 120
    - 60
    - 30
    - 15
    - 7.5
    - 3.750
    - 1.875
    - 1.0
    - 0.5
    - 0.250
    - 0.125
SpectralFrameScale: []
MaxTilesPerSuperTile: 12
UseDistributionsForNormalization: false
LdSpectrogramConfig:
    ColorMap1: "ACI-ENT-EVN" 
    ColorMap2: "BGN-PMN-EVN"
    # seconds
    XAxisTicIntervalSeconds: 3600
    # Hertz
    YAxisTicInterval: 1000
IndexPropertiesConfig: './IndexPropertiesConfig.HiRes.yml'
...