---
  UnitsOfTime: "second"
  IndexCalculationDuration: 0.2
  SpectralFrameDuration: 0.02
  TileWidth: 300
  ScaleUnits: "SecondsPerPixel"
  SpectralIndexScale: 
    - 60
    - 24
    - 12
    - 6
    - 2
    - 1
    - 0.6
    - 0.2
  SpectralFrameScale: 
    - 0.1
    - 0.04
    - 0.02
  MaxTilesPerSuperTile: 12
...