---
SpectralFrameDuration: 0.02
TileWidth: 300
# How to tile, valid values:
# - PanoJsTilingProfile
# - AbsoluteDateTilingProfile
TilingProfile: AbsoluteDateTilingProfile
SpectralIndexScale: 
    - 60
    - 24
    - 12
    - 6
    - 4
    - 2
    - 1
    - 0.6
    - 0.4
    - 0.2
SpectralFrameScale:
    - 0.07
    - 0.04
    - 0.02
MaxTilesPerSuperTile: 12
UseDistributionsForNormalization: false
LdSpectrogramConfig:
    ColorMap1: "ACI-ENT-EVN" 
    ColorMap2: "BGN-POW-EVN"
    # minutes
    XAxisTicIntervalSeconds: 3600
    # Hertz
    YAxisTicInterval: 1000
IndexPropertiesConfig: './IndexPropertiesConfigForZooming.yml'
...