---
SpectralFrameDuration: 0.02
TileWidth: 180
# How to tile, valid values:
# - PanoJsTilingProfile
# - AbsoluteDateTilingProfile
TilingProfile: AbsoluteDateTilingProfile
SpectralIndexScale: 
    - 240
    - 120
    - 60
    - 30
    - 15
    - 7.5
    - 3.2
    - 1.6
    - 0.8
    - 0.4
    - 0.2
    - 0.1
SpectralFrameScale: []
MaxTilesPerSuperTile: 12
UseDistributionsForNormalization: false
LdSpectrogramConfig:
    ColorMap1: "ACI-ENT-EVN" 
    ColorMap2: "BGN-PMN-EVN"
    # seconds
    XAxisTicIntervalSeconds: 3600
    # Hertz
    YAxisTicInterval: 1000
IndexPropertiesConfig: './IndexPropertiesConfig.Zooming.yml'
...