---
# This config can be used to control the drawing of long duration false-colour Spectrograms
# It should NOT contain index related configuration data
# It should NOT contain dynamic data (like file names or analysis types)

ColorMap1: "ACI-ENT-EVN" 
ColorMap2: "BGN-POW-SPT"
#ColorMap1 = "ACI-TEN-CVR"
#ColorMap2 = "BGN-AVG-VAR"
#ColorMap2 = "BGN-POW-CVR"
#ColorMap2 = "BGN-POW-RHZ"


# Determines colour intensity of the lower index values relative to the higher index values. Good value is 0.75
ColourGain: 2.0
ColourFilter: 0.75

# minutes x-axis scale
XAxisTicInterval: 60

# Hertz y-axis scale
YAxisTicInterval: 1000

...