//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QutSensors.Processor.WebServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Processor.JobItemDescription", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ProcessorJobItemDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AudioReadingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QutSensors.Processor.WebServices.ProcessorJobDescription JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AudioReadingUrl {
            get {
                return this.AudioReadingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AudioReadingUrlField, value) != true)) {
                    this.AudioReadingUrlField = value;
                    this.RaisePropertyChanged("AudioReadingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QutSensors.Processor.WebServices.ProcessorJobDescription Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobItemID {
            get {
                return this.JobItemIDField;
            }
            set {
                if ((this.JobItemIDField.Equals(value) != true)) {
                    this.JobItemIDField = value;
                    this.RaisePropertyChanged("JobItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType {
            get {
                return this.MimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeTypeField, value) != true)) {
                    this.MimeTypeField = value;
                    this.RaisePropertyChanged("MimeType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Processor.JobDescription", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ProcessorJobDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessorTypeSettingsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobID {
            get {
                return this.JobIDField;
            }
            set {
                if ((this.JobIDField.Equals(value) != true)) {
                    this.JobIDField = value;
                    this.RaisePropertyChanged("JobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessorTypeSettings {
            get {
                return this.ProcessorTypeSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessorTypeSettingsField, value) != true)) {
                    this.ProcessorTypeSettingsField = value;
                    this.RaisePropertyChanged("ProcessorTypeSettings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Processor.JobItemResult", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ProcessorJobItemResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RankingScoreLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RankingScoreNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RankingScoreValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StopField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RankingScoreLocation {
            get {
                return this.RankingScoreLocationField;
            }
            set {
                if ((this.RankingScoreLocationField.Equals(value) != true)) {
                    this.RankingScoreLocationField = value;
                    this.RaisePropertyChanged("RankingScoreLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RankingScoreName {
            get {
                return this.RankingScoreNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RankingScoreNameField, value) != true)) {
                    this.RankingScoreNameField = value;
                    this.RaisePropertyChanged("RankingScoreName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RankingScoreValue {
            get {
                return this.RankingScoreValueField;
            }
            set {
                if ((this.RankingScoreValueField.Equals(value) != true)) {
                    this.RankingScoreValueField = value;
                    this.RaisePropertyChanged("RankingScoreValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stop {
            get {
                return this.StopField;
            }
            set {
                if ((this.StopField.Equals(value) != true)) {
                    this.StopField = value;
                    this.RaisePropertyChanged("Stop");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="sensor.mquter.qut.edu.au", ConfigurationName="WebServices.Processor")]
    public interface Processor {
        
        [System.ServiceModel.OperationContractAttribute(Action="sensor.mquter.qut.edu.au/Processor/GetJobItem", ReplyAction="sensor.mquter.qut.edu.au/Processor/GetJobItemResponse")]
        QutSensors.Processor.WebServices.GetJobItemResponse GetJobItem(QutSensors.Processor.WebServices.GetJobItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="sensor.mquter.qut.edu.au/Processor/GetJobItem", ReplyAction="sensor.mquter.qut.edu.au/Processor/GetJobItemResponse")]
        System.IAsyncResult BeginGetJobItem(QutSensors.Processor.WebServices.GetJobItemRequest request, System.AsyncCallback callback, object asyncState);
        
        QutSensors.Processor.WebServices.GetJobItemResponse EndGetJobItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="sensor.mquter.qut.edu.au/Processor/SubmitResults", ReplyAction="sensor.mquter.qut.edu.au/Processor/SubmitResultsResponse")]
        QutSensors.Processor.WebServices.SubmitResultsResponse SubmitResults(QutSensors.Processor.WebServices.SubmitResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="sensor.mquter.qut.edu.au/Processor/SubmitResults", ReplyAction="sensor.mquter.qut.edu.au/Processor/SubmitResultsResponse")]
        System.IAsyncResult BeginSubmitResults(QutSensors.Processor.WebServices.SubmitResultsRequest request, System.AsyncCallback callback, object asyncState);
        
        QutSensors.Processor.WebServices.SubmitResultsResponse EndSubmitResults(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="sensor.mquter.qut.edu.au/Processor/SubmitJobItemResults", ReplyAction="sensor.mquter.qut.edu.au/Processor/SubmitJobItemResultsResponse")]
        QutSensors.Processor.WebServices.SubmitJobItemResultsResponse SubmitJobItemResults(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="sensor.mquter.qut.edu.au/Processor/SubmitJobItemResults", ReplyAction="sensor.mquter.qut.edu.au/Processor/SubmitJobItemResultsResponse")]
        System.IAsyncResult BeginSubmitJobItemResults(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request, System.AsyncCallback callback, object asyncState);
        
        QutSensors.Processor.WebServices.SubmitJobItemResultsResponse EndSubmitJobItemResults(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="sensor.mquter.qut.edu.au/Processor/ReturnJob", ReplyAction="sensor.mquter.qut.edu.au/Processor/ReturnJobResponse")]
        QutSensors.Processor.WebServices.ReturnJobResponse ReturnJob(QutSensors.Processor.WebServices.ReturnJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="sensor.mquter.qut.edu.au/Processor/ReturnJob", ReplyAction="sensor.mquter.qut.edu.au/Processor/ReturnJobResponse")]
        System.IAsyncResult BeginReturnJob(QutSensors.Processor.WebServices.ReturnJobRequest request, System.AsyncCallback callback, object asyncState);
        
        QutSensors.Processor.WebServices.ReturnJobResponse EndReturnJob(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="sensor.mquter.qut.edu.au/Processor/ReturnJobWithError", ReplyAction="sensor.mquter.qut.edu.au/Processor/ReturnJobWithErrorResponse")]
        QutSensors.Processor.WebServices.ReturnJobWithErrorResponse ReturnJobWithError(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="sensor.mquter.qut.edu.au/Processor/ReturnJobWithError", ReplyAction="sensor.mquter.qut.edu.au/Processor/ReturnJobWithErrorResponse")]
        System.IAsyncResult BeginReturnJobWithError(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request, System.AsyncCallback callback, object asyncState);
        
        QutSensors.Processor.WebServices.ReturnJobWithErrorResponse EndReturnJobWithError(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobItem", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class GetJobItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public string worker;
        
        public GetJobItemRequest() {
        }
        
        public GetJobItemRequest(string worker) {
            this.worker = worker;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetJobItemResponse", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class GetJobItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public QutSensors.Processor.WebServices.ProcessorJobItemDescription GetJobItemResult;
        
        public GetJobItemResponse() {
        }
        
        public GetJobItemResponse(QutSensors.Processor.WebServices.ProcessorJobItemDescription GetJobItemResult) {
            this.GetJobItemResult = GetJobItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitResults", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class SubmitResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=1)]
        public int jobItemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=2)]
        public QutSensors.Processor.WebServices.ProcessorJobItemResult[] results;
        
        public SubmitResultsRequest() {
        }
        
        public SubmitResultsRequest(string worker, int jobItemID, QutSensors.Processor.WebServices.ProcessorJobItemResult[] results) {
            this.worker = worker;
            this.jobItemID = jobItemID;
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitResultsResponse", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class SubmitResultsResponse {
        
        public SubmitResultsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitJobItemResults", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class SubmitJobItemResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public int jobItemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=1)]
        public QutSensors.Data.Logic.ProcessorResultTag[] results;
        
        public SubmitJobItemResultsRequest() {
        }
        
        public SubmitJobItemResultsRequest(int jobItemID, QutSensors.Data.Logic.ProcessorResultTag[] results) {
            this.jobItemID = jobItemID;
            this.results = results;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitJobItemResultsResponse", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class SubmitJobItemResultsResponse {
        
        public SubmitJobItemResultsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnJob", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class ReturnJobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=1)]
        public int jobItemID;
        
        public ReturnJobRequest() {
        }
        
        public ReturnJobRequest(string worker, int jobItemID) {
            this.worker = worker;
            this.jobItemID = jobItemID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnJobResponse", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class ReturnJobResponse {
        
        public ReturnJobResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnJobWithError", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class ReturnJobWithErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=0)]
        public string worker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=1)]
        public int jobItemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="sensor.mquter.qut.edu.au", Order=2)]
        public string errorDetails;
        
        public ReturnJobWithErrorRequest() {
        }
        
        public ReturnJobWithErrorRequest(string worker, int jobItemID, string errorDetails) {
            this.worker = worker;
            this.jobItemID = jobItemID;
            this.errorDetails = errorDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnJobWithErrorResponse", WrapperNamespace="sensor.mquter.qut.edu.au", IsWrapped=true)]
    public partial class ReturnJobWithErrorResponse {
        
        public ReturnJobWithErrorResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ProcessorChannel : QutSensors.Processor.WebServices.Processor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetJobItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetJobItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QutSensors.Processor.WebServices.GetJobItemResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QutSensors.Processor.WebServices.GetJobItemResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SubmitResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QutSensors.Processor.WebServices.SubmitResultsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QutSensors.Processor.WebServices.SubmitResultsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SubmitJobItemResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitJobItemResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QutSensors.Processor.WebServices.SubmitJobItemResultsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QutSensors.Processor.WebServices.SubmitJobItemResultsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReturnJobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReturnJobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QutSensors.Processor.WebServices.ReturnJobResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QutSensors.Processor.WebServices.ReturnJobResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReturnJobWithErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReturnJobWithErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QutSensors.Processor.WebServices.ReturnJobWithErrorResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QutSensors.Processor.WebServices.ReturnJobWithErrorResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProcessorClient : System.ServiceModel.ClientBase<QutSensors.Processor.WebServices.Processor>, QutSensors.Processor.WebServices.Processor {
        
        private BeginOperationDelegate onBeginGetJobItemDelegate;
        
        private EndOperationDelegate onEndGetJobItemDelegate;
        
        private System.Threading.SendOrPostCallback onGetJobItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitResultsDelegate;
        
        private EndOperationDelegate onEndSubmitResultsDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitResultsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitJobItemResultsDelegate;
        
        private EndOperationDelegate onEndSubmitJobItemResultsDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitJobItemResultsCompletedDelegate;
        
        private BeginOperationDelegate onBeginReturnJobDelegate;
        
        private EndOperationDelegate onEndReturnJobDelegate;
        
        private System.Threading.SendOrPostCallback onReturnJobCompletedDelegate;
        
        private BeginOperationDelegate onBeginReturnJobWithErrorDelegate;
        
        private EndOperationDelegate onEndReturnJobWithErrorDelegate;
        
        private System.Threading.SendOrPostCallback onReturnJobWithErrorCompletedDelegate;
        
        public ProcessorClient() {
        }
        
        public ProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetJobItemCompletedEventArgs> GetJobItemCompleted;
        
        public event System.EventHandler<SubmitResultsCompletedEventArgs> SubmitResultsCompleted;
        
        public event System.EventHandler<SubmitJobItemResultsCompletedEventArgs> SubmitJobItemResultsCompleted;
        
        public event System.EventHandler<ReturnJobCompletedEventArgs> ReturnJobCompleted;
        
        public event System.EventHandler<ReturnJobWithErrorCompletedEventArgs> ReturnJobWithErrorCompleted;
        
        public QutSensors.Processor.WebServices.GetJobItemResponse GetJobItem(QutSensors.Processor.WebServices.GetJobItemRequest request) {
            return base.Channel.GetJobItem(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetJobItem(QutSensors.Processor.WebServices.GetJobItemRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetJobItem(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QutSensors.Processor.WebServices.GetJobItemResponse EndGetJobItem(System.IAsyncResult result) {
            return base.Channel.EndGetJobItem(result);
        }
        
        private System.IAsyncResult OnBeginGetJobItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QutSensors.Processor.WebServices.GetJobItemRequest request = ((QutSensors.Processor.WebServices.GetJobItemRequest)(inValues[0]));
            return this.BeginGetJobItem(request, callback, asyncState);
        }
        
        private object[] OnEndGetJobItem(System.IAsyncResult result) {
            QutSensors.Processor.WebServices.GetJobItemResponse retVal = this.EndGetJobItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetJobItemCompleted(object state) {
            if ((this.GetJobItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetJobItemCompleted(this, new GetJobItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetJobItemAsync(QutSensors.Processor.WebServices.GetJobItemRequest request) {
            this.GetJobItemAsync(request, null);
        }
        
        public void GetJobItemAsync(QutSensors.Processor.WebServices.GetJobItemRequest request, object userState) {
            if ((this.onBeginGetJobItemDelegate == null)) {
                this.onBeginGetJobItemDelegate = new BeginOperationDelegate(this.OnBeginGetJobItem);
            }
            if ((this.onEndGetJobItemDelegate == null)) {
                this.onEndGetJobItemDelegate = new EndOperationDelegate(this.OnEndGetJobItem);
            }
            if ((this.onGetJobItemCompletedDelegate == null)) {
                this.onGetJobItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetJobItemCompleted);
            }
            base.InvokeAsync(this.onBeginGetJobItemDelegate, new object[] {
                        request}, this.onEndGetJobItemDelegate, this.onGetJobItemCompletedDelegate, userState);
        }
        
        public QutSensors.Processor.WebServices.SubmitResultsResponse SubmitResults(QutSensors.Processor.WebServices.SubmitResultsRequest request) {
            return base.Channel.SubmitResults(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSubmitResults(QutSensors.Processor.WebServices.SubmitResultsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitResults(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QutSensors.Processor.WebServices.SubmitResultsResponse EndSubmitResults(System.IAsyncResult result) {
            return base.Channel.EndSubmitResults(result);
        }
        
        private System.IAsyncResult OnBeginSubmitResults(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QutSensors.Processor.WebServices.SubmitResultsRequest request = ((QutSensors.Processor.WebServices.SubmitResultsRequest)(inValues[0]));
            return this.BeginSubmitResults(request, callback, asyncState);
        }
        
        private object[] OnEndSubmitResults(System.IAsyncResult result) {
            QutSensors.Processor.WebServices.SubmitResultsResponse retVal = this.EndSubmitResults(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitResultsCompleted(object state) {
            if ((this.SubmitResultsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitResultsCompleted(this, new SubmitResultsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitResultsAsync(QutSensors.Processor.WebServices.SubmitResultsRequest request) {
            this.SubmitResultsAsync(request, null);
        }
        
        public void SubmitResultsAsync(QutSensors.Processor.WebServices.SubmitResultsRequest request, object userState) {
            if ((this.onBeginSubmitResultsDelegate == null)) {
                this.onBeginSubmitResultsDelegate = new BeginOperationDelegate(this.OnBeginSubmitResults);
            }
            if ((this.onEndSubmitResultsDelegate == null)) {
                this.onEndSubmitResultsDelegate = new EndOperationDelegate(this.OnEndSubmitResults);
            }
            if ((this.onSubmitResultsCompletedDelegate == null)) {
                this.onSubmitResultsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitResultsCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitResultsDelegate, new object[] {
                        request}, this.onEndSubmitResultsDelegate, this.onSubmitResultsCompletedDelegate, userState);
        }
        
        public QutSensors.Processor.WebServices.SubmitJobItemResultsResponse SubmitJobItemResults(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request) {
            return base.Channel.SubmitJobItemResults(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSubmitJobItemResults(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitJobItemResults(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QutSensors.Processor.WebServices.SubmitJobItemResultsResponse EndSubmitJobItemResults(System.IAsyncResult result) {
            return base.Channel.EndSubmitJobItemResults(result);
        }
        
        private System.IAsyncResult OnBeginSubmitJobItemResults(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request = ((QutSensors.Processor.WebServices.SubmitJobItemResultsRequest)(inValues[0]));
            return this.BeginSubmitJobItemResults(request, callback, asyncState);
        }
        
        private object[] OnEndSubmitJobItemResults(System.IAsyncResult result) {
            QutSensors.Processor.WebServices.SubmitJobItemResultsResponse retVal = this.EndSubmitJobItemResults(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitJobItemResultsCompleted(object state) {
            if ((this.SubmitJobItemResultsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitJobItemResultsCompleted(this, new SubmitJobItemResultsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitJobItemResultsAsync(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request) {
            this.SubmitJobItemResultsAsync(request, null);
        }
        
        public void SubmitJobItemResultsAsync(QutSensors.Processor.WebServices.SubmitJobItemResultsRequest request, object userState) {
            if ((this.onBeginSubmitJobItemResultsDelegate == null)) {
                this.onBeginSubmitJobItemResultsDelegate = new BeginOperationDelegate(this.OnBeginSubmitJobItemResults);
            }
            if ((this.onEndSubmitJobItemResultsDelegate == null)) {
                this.onEndSubmitJobItemResultsDelegate = new EndOperationDelegate(this.OnEndSubmitJobItemResults);
            }
            if ((this.onSubmitJobItemResultsCompletedDelegate == null)) {
                this.onSubmitJobItemResultsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitJobItemResultsCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitJobItemResultsDelegate, new object[] {
                        request}, this.onEndSubmitJobItemResultsDelegate, this.onSubmitJobItemResultsCompletedDelegate, userState);
        }
        
        public QutSensors.Processor.WebServices.ReturnJobResponse ReturnJob(QutSensors.Processor.WebServices.ReturnJobRequest request) {
            return base.Channel.ReturnJob(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReturnJob(QutSensors.Processor.WebServices.ReturnJobRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReturnJob(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QutSensors.Processor.WebServices.ReturnJobResponse EndReturnJob(System.IAsyncResult result) {
            return base.Channel.EndReturnJob(result);
        }
        
        private System.IAsyncResult OnBeginReturnJob(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QutSensors.Processor.WebServices.ReturnJobRequest request = ((QutSensors.Processor.WebServices.ReturnJobRequest)(inValues[0]));
            return this.BeginReturnJob(request, callback, asyncState);
        }
        
        private object[] OnEndReturnJob(System.IAsyncResult result) {
            QutSensors.Processor.WebServices.ReturnJobResponse retVal = this.EndReturnJob(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReturnJobCompleted(object state) {
            if ((this.ReturnJobCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReturnJobCompleted(this, new ReturnJobCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReturnJobAsync(QutSensors.Processor.WebServices.ReturnJobRequest request) {
            this.ReturnJobAsync(request, null);
        }
        
        public void ReturnJobAsync(QutSensors.Processor.WebServices.ReturnJobRequest request, object userState) {
            if ((this.onBeginReturnJobDelegate == null)) {
                this.onBeginReturnJobDelegate = new BeginOperationDelegate(this.OnBeginReturnJob);
            }
            if ((this.onEndReturnJobDelegate == null)) {
                this.onEndReturnJobDelegate = new EndOperationDelegate(this.OnEndReturnJob);
            }
            if ((this.onReturnJobCompletedDelegate == null)) {
                this.onReturnJobCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReturnJobCompleted);
            }
            base.InvokeAsync(this.onBeginReturnJobDelegate, new object[] {
                        request}, this.onEndReturnJobDelegate, this.onReturnJobCompletedDelegate, userState);
        }
        
        public QutSensors.Processor.WebServices.ReturnJobWithErrorResponse ReturnJobWithError(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request) {
            return base.Channel.ReturnJobWithError(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReturnJobWithError(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReturnJobWithError(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public QutSensors.Processor.WebServices.ReturnJobWithErrorResponse EndReturnJobWithError(System.IAsyncResult result) {
            return base.Channel.EndReturnJobWithError(result);
        }
        
        private System.IAsyncResult OnBeginReturnJobWithError(object[] inValues, System.AsyncCallback callback, object asyncState) {
            QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request = ((QutSensors.Processor.WebServices.ReturnJobWithErrorRequest)(inValues[0]));
            return this.BeginReturnJobWithError(request, callback, asyncState);
        }
        
        private object[] OnEndReturnJobWithError(System.IAsyncResult result) {
            QutSensors.Processor.WebServices.ReturnJobWithErrorResponse retVal = this.EndReturnJobWithError(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReturnJobWithErrorCompleted(object state) {
            if ((this.ReturnJobWithErrorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReturnJobWithErrorCompleted(this, new ReturnJobWithErrorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReturnJobWithErrorAsync(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request) {
            this.ReturnJobWithErrorAsync(request, null);
        }
        
        public void ReturnJobWithErrorAsync(QutSensors.Processor.WebServices.ReturnJobWithErrorRequest request, object userState) {
            if ((this.onBeginReturnJobWithErrorDelegate == null)) {
                this.onBeginReturnJobWithErrorDelegate = new BeginOperationDelegate(this.OnBeginReturnJobWithError);
            }
            if ((this.onEndReturnJobWithErrorDelegate == null)) {
                this.onEndReturnJobWithErrorDelegate = new EndOperationDelegate(this.OnEndReturnJobWithError);
            }
            if ((this.onReturnJobWithErrorCompletedDelegate == null)) {
                this.onReturnJobWithErrorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReturnJobWithErrorCompleted);
            }
            base.InvokeAsync(this.onBeginReturnJobWithErrorDelegate, new object[] {
                        request}, this.onEndReturnJobWithErrorDelegate, this.onReturnJobWithErrorCompletedDelegate, userState);
        }
    }
}
